$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
  trimming:
    type: object
    properties:
      skip:
        type: boolean
      adapter:
        type: string
        pattern: "^[ACGT]+$"
      contaminant_files:
        type: array

  ref:
    type: object
    properties:
      star_index:
        type: string
      kallisto_index:
        type: string
      transcripts_to_genes:
        type: string
      annotation:
        type: string
    required:
      - star_index
      - kallisto_index
      - transcripts_to_genes
      - annotation

  diffexp:
    type: object
    properties:
      contrasts:
        type: object
    required:
      - contrasts

  params:
    type: object
    properties:
      star:
        type: string
      cutadapt-se:
        type: string
      cutadapt-pe:
        type: string
      bbtrim:
        type: string
      kallisto:
        type: object
      deseq2:
        type: object
        
    required:
      - star
      - cutadapt-se
      - cutadapt-pe
      - bbtrim
      - kallisto

required:
  - samples
  - units
  - trimming
  - ref
  - diffexp
  - params
